### ISSUE TITLE
Build jekyll template to bring in other languages

### ISSUE THREAD

**Issue by ErnieAtLYD** [mangrove-labs/cutgroup-website#1]
#### Description

This website is built in Jekyll and github pages. The content needs to be in Spanish and maybe Haitian Creole, because Miami. What's an easy way we can bring this in?
#### Tasks

Because this site is built on github pages and jekyll, one way we can do this is making the static page and building markdown templates putting the content in different languages. Or we can just fork a different version and two repos! Whatever works best for people.
- [ ] Translate content in Spanish
- [ ] Translate content in Haitian Kreyol (optional)
- [ ] Build out a language chooser in the navigation in HTML
- [ ] Build out jekyll templates
#### Links
- https://www.sylvaindurand.org/making-jekyll-multilingual/
- https://github.com/sylvaindurand/jekyll-multilingual
